version: '3.8'
services:
  mongodb:
    image: "mongo"
    volumes:
      - "mongodb_data:/data/db"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 6s
      timeout: 30s
      retries: 10

  api-service:
    build:
      context: ./back/api-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      WORKFLOW_URL: http://workflow-service
      DOC_URL: http://document-service
      CODERUNNER_URL: http://coderunner-service

  coderunner-service:
    build:
      context: ./back/coderunner-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  document-service:
    build:
      context: ./back/document-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://user:pass@mongodb:27017

  workflow-service:
    build:
      context: ./back/workflow-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://user:pass@mongodb:27017

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile

volumes:
  mongodb_data:
