version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - "mongodb_data:/data/db"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 6s
      timeout: 30s
      retries: 10

  mongo-express:
    image: "mongo-express"
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: adminpass
    depends_on:
      mongodb:
        condition: service_healthy

  api-service:
    build:
      context: ./back/api-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      WORKFLOW_URL: http://workflow-service:8003
      DOC_URL: http://document-service:8002
      CODERUNNER_URL: http://coderunner-service:8001

  coderunner-service:
    build:
      context: ./back/coderunner-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WORKFLOW_URL: http://workflow-service:8003
      DOC_URL: http://document-service:8002

  document-service:
    build:
      context: ./back/document-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://user:pass@mongodb:27017

  workflow-service:
    build:
      context: ./back/workflow-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://user:pass@mongodb:27017

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      API_URI: http://api-service

volumes:
  mongodb_data:
